2024-11-20 14:57:30,242 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\_Documents\UrbanProg\module_12_4\tests_12_4.py", line 29, in test_run
    r_obj = module_12_4.Runner(['Roman', 'Anton'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Documents\UrbanProg\module_12_4\module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2024-11-20 14:57:30,243 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\_Documents\UrbanProg\module_12_4\tests_12_4.py", line 15, in test_walk
    r_obj = module_12_4.Runner('Roman', -5)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Documents\UrbanProg\module_12_4\module_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
